/**
 * Initial Construction ERP Data Seed
 * S.M. Khalilur Rahman Properties Ltd.
 */
import { 
  Project, 
  Account, 
  Contractor, 
  Supplier, 
  Expense, 
  MoneyReceived, 
  Loan, 
  MonthlyCompanyExpense, 
  Voucher, 
  LedgerEntry, 
  AuditLog, 
  CompanySettings,
  UserProfile,
  MaterialItem
} from '../types';
import { convertNumberToWordsBn, convertNumberToWordsEn } from '../utils/numberToWords';

export const initialCompanySettings: CompanySettings = {
  companyName: 'S.M. Khalilur Rahman Properties Ltd.',
  companyNameBn: 'এস. এম. খলিলুর রহমান প্রপার্টিজ লিঃ',
  erpTitle: 'Construction Accounts & Project ERP',
  erpTitleBn: 'কনস্ট্রাকশন অ্যাকাউন্টস ও প্রজেক্ট ইআরপি',
  address: '21, 22 Durgabari Road, Mymensingh',
  addressBn: '২১, ২২ দুর্গাবাড়ি রোড, ময়মনসিংহ',
  phone: '01672965561',
  email: 'info@skrpproperties.com',
  allowNegativeBalance: false,
  autoGenerateVouchers: true,
  currencySymbol: '৳',
};

export const initialProjects: Project[] = [
  {
    id: 'prj-tokyo-a',
    name: 'Tokyo Square Convention Center - Project A',
    code: 'TS-PRJ-A',
    client: 'S.M. Khalilur Rahman Properties Ltd.',
    location: 'Plot 12, Ring Road, Mohammadpur, Dhaka',
    startDate: '2026-01-01',
    expectedEndDate: '2027-06-30',
    budget: 5000000,
    spent: 0,
    status: 'Running',
    description: 'Modern Commercial Convention Center with basement parking and multi-level banquet halls.',
    projectManager: 'Tutul Ahmed',
    materialCost: 0,
    labourCost: 0,
    contractorCost: 0,
    otherCost: 0,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-30T08:00:00Z',
  }
];

export const initialAccounts: Account[] = [
  {
    id: 'acc-cash-01',
    name: 'Cash in Hand (প্রধান ক্যাশ বক্স)',
    type: 'CASH',
    openingBalance: 150000,
    totalReceived: 2500000,
    totalPaid: 2325000,
    currentBalance: 325000,
    isDefault: true,
  },
  {
    id: 'acc-bank-city',
    name: 'City Bank Ltd. (A/C: 110-239485)',
    type: 'BANK',
    accountNumber: '110-239485',
    bankName: 'City Bank Ltd.',
    branch: 'Mohammadpur Branch, Dhaka',
    openingBalance: 500000,
    totalReceived: 4200000,
    totalPaid: 4375000,
    currentBalance: 325000,
  }
];

export const initialContractors: Contractor[] = [
  {
    id: 'cnt-carpenter-01',
    name: 'Rafiqul Islam (Carpenter Mistry)',
    type: 'CARPENTER',
    phone: '+880 1712-345678',
    address: 'Mohammadpur, Dhaka',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    contractAmount: 300000,
    totalBill: 200000,
    paidAmount: 120000,
    dueAmount: 180000,
    status: 'Active',
    startDate: '2026-02-01',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'cnt-electric-02',
    name: 'Abul Kalam (Electrical Contractor)',
    type: 'ELECTRICIAN',
    phone: '+880 1819-456789',
    address: 'Adabor, Dhaka',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    contractAmount: 500000,
    totalBill: 400000,
    paidAmount: 320000,
    dueAmount: 180000,
    status: 'Active',
    startDate: '2026-02-15',
    createdAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'cnt-paint-03',
    name: 'Zahangir Alam (Painting Contractor)',
    type: 'PAINTER',
    phone: '+880 1911-567890',
    address: 'Shyamoli, Dhaka',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    contractAmount: 250000,
    totalBill: 150000,
    paidAmount: 100000,
    dueAmount: 150000,
    status: 'Active',
    startDate: '2026-03-01',
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cnt-plumb-04',
    name: 'Monir Hossain (Plumbing Contractor)',
    type: 'PLUMBER',
    phone: '+880 1612-678901',
    address: 'Rayerbazar, Dhaka',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    contractAmount: 350000,
    totalBill: 200000,
    paidAmount: 150000,
    dueAmount: 200000,
    status: 'Active',
    startDate: '2026-03-15',
    createdAt: '2026-03-15T08:00:00Z',
  }
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-rahman-01',
    name: 'Rahman Traders (Cement & Sand)',
    phone: '+880 1715-112233',
    address: 'Gabtoli Beribadh, Dhaka',
    type: 'CEMENT',
    openingDue: 50000,
    totalPurchase: 650000,
    totalPaid: 580000,
    currentDue: 120000,
    notes: 'Primary supplier for Crown & Shah Cement',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'sup-bsrm-02',
    name: 'Meghna Steel & Rod Enterprise',
    phone: '+880 1817-223344',
    address: 'Postogola, Dhaka',
    type: 'ROD',
    openingDue: 0,
    totalPurchase: 1200000,
    totalPaid: 1100000,
    currentDue: 100000,
    notes: '72 Grade BSRM Rod Supplier',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'sup-holcim-03',
    name: 'Dhaka Brick Field Co.',
    phone: '+880 1918-334455',
    address: 'Savar, Dhaka',
    type: 'BRICK',
    openingDue: 0,
    totalPurchase: 450000,
    totalPaid: 400000,
    currentDue: 50000,
    notes: 'Auto Brick 1st Class',
    createdAt: '2026-02-01T08:00:00Z',
  }
];

export const initialMoneyReceived: MoneyReceived[] = [
  {
    id: 'rec-001',
    receiptNumber: 'MR-2026-00001',
    date: '2026-08-01',
    receivedFrom: 'Japan Garden City Ltd.',
    sourceType: 'Japan Garden City',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    amount: 1500000,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    reference: 'CHQ# 982341 - City Bank',
    description: 'Phase 2 Construction Installment funding from Japan Garden City.',
    createdAt: '2026-08-01T10:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'rec-002',
    receiptNumber: 'MR-2026-00002',
    date: '2026-08-05',
    receivedFrom: 'Japan City Tower Authority',
    sourceType: 'Japan City Tower',
    projectId: 'prj-japan-tower',
    projectName: 'Japan City Tower - Commercial Complex',
    amount: 2500000,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    reference: 'FT-JCT-2026-881',
    description: 'Project construction fund contribution for Japan City Tower.',
    createdAt: '2026-08-05T09:30:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'rec-003',
    receiptNumber: 'MR-2026-00003',
    date: '2026-08-10',
    receivedFrom: 'Eng. S.M. Khalilur Rahman (Owner)',
    sourceType: 'Owner',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    amount: 1000000,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    reference: 'Direct Owner Contribution',
    description: 'Emergency project running cost contribution.',
    createdAt: '2026-08-10T11:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'rec-004',
    receiptNumber: 'MR-2026-00004',
    date: '2026-08-12',
    receivedFrom: 'Dr. K.R. Islam (Dr. Kayer Islam)',
    sourceType: 'Loan',
    projectId: 'prj-japan-tower',
    projectName: 'Japan City Tower - Commercial Complex',
    amount: 800000,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    reference: 'PO# 441029 - Islami Bank',
    description: 'Short-term project loan from Dr. K.R. Islam for material purchase.',
    createdAt: '2026-08-12T14:15:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'rec-005',
    receiptNumber: 'MR-2026-00005',
    date: '2026-08-15',
    receivedFrom: 'Raihan Sir',
    sourceType: 'Share Voucher / Partner',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    amount: 1200000,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    reference: 'Share Deposit #012',
    description: 'Partner equity contribution from Raihan Sir.',
    createdAt: '2026-08-15T11:20:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'rec-006',
    receiptNumber: 'MR-2026-00006',
    date: '2026-08-18',
    receivedFrom: 'Honorable Madam',
    sourceType: 'Director',
    projectId: 'prj-japan-tower',
    projectName: 'Japan City Tower - Commercial Complex',
    amount: 700000,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    reference: 'Director Fund Deposit',
    description: 'Director fund contribution from Honorable Madam for site operations.',
    createdAt: '2026-08-18T16:00:00Z',
    createdBy: 'MD. eleyes',
  }
];

export const initialLoans: Loan[] = [
  {
    id: 'loan-001',
    lenderName: 'Dr. K.R. Islam (Dr. Kayer Islam)',
    date: '2026-07-15',
    amount: 800000,
    projectId: 'prj-japan-tower',
    projectName: 'Japan City Tower - Commercial Complex',
    purpose: 'Short-term bridge funding for steel & cement procurement',
    paymentMethod: 'BANK',
    repaymentAmount: 300000,
    outstandingAmount: 500000,
    status: 'PARTIALLY_PAID',
    reference: 'Agreement Doc #094',
    createdAt: '2026-07-15T09:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'loan-002',
    lenderName: 'Raihan Sir (Ruhul Amin)',
    date: '2026-08-05',
    amount: 500000,
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    purpose: 'Urgent material booking loan',
    paymentMethod: 'CASH',
    repaymentAmount: 200000,
    outstandingAmount: 300000,
    status: 'PARTIALLY_PAID',
    reference: 'Voucher Note #88',
    createdAt: '2026-08-05T14:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'loan-003',
    lenderName: 'Honorable Madam Loan Account',
    date: '2026-08-10',
    amount: 400000,
    projectId: 'prj-japan-tower',
    projectName: 'Japan City Tower - Commercial Complex',
    purpose: 'Emergency site contractor payment loan',
    paymentMethod: 'CASH',
    repaymentAmount: 400000,
    outstandingAmount: 0,
    status: 'FULLY_PAID',
    reference: 'Personal Cash Loan',
    createdAt: '2026-08-10T10:00:00Z',
    createdBy: 'MD. eleyes',
  }
];

export const initialMonthlyBills: MonthlyCompanyExpense[] = [
  {
    id: 'bill-001',
    month: 'August 2026',
    year: 2026,
    expenseName: 'MD. eleyes',
    category: 'SALARY',
    amount: 45000,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    description: 'Monthly salary for August 2026',
    voucherId: 'vch-sal-01',
    voucherNumber: 'CPV-2026-000101',
    createdAt: '2026-08-25T10:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'bill-002',
    month: 'August 2026',
    year: 2026,
    expenseName: 'Tutul',
    category: 'CONVEYANCE',
    amount: 12000,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    description: 'Site travel and municipal paperwork conveyance bill',
    voucherId: 'vch-con-02',
    voucherNumber: 'CPV-2026-000102',
    createdAt: '2026-08-26T12:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'bill-003',
    month: 'August 2026',
    year: 2026,
    expenseName: 'Tutul Food Bill (Site Staff & Workers Lunch)',
    category: 'FOOD',
    amount: 15500,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    description: 'Site technical supervision food & tea bill for August',
    voucherId: 'vch-foo-03',
    voucherNumber: 'CPV-2026-000103',
    createdAt: '2026-08-27T16:00:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'bill-004',
    month: 'August 2026',
    year: 2026,
    expenseName: 'Tokyo Square Site Electricity Bill',
    category: 'ELECTRICITY',
    amount: 28400,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    description: 'DESCO electricity bill for heavy crane and welding plant',
    voucherId: 'vch-ele-04',
    voucherNumber: 'CPV-2026-000104',
    createdAt: '2026-08-28T09:00:00Z',
    createdBy: 'MD. Ilyas',
  }
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-001',
    date: '2026-08-30',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    expenseType: 'MATERIAL',
    category: 'CEMENT',
    subcategory: 'Crown Portland Cement (50 Bags)',
    paidTo: 'Rahman Traders',
    supplierId: 'sup-rahman-01',
    supplierName: 'Rahman Traders',
    amount: 25000,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    description: '50 bags Crown Cement for 3rd floor casting.',
    reference: 'Bill #RT-9982',
    voucherId: 'vch-00125',
    voucherNumber: 'CPV-2026-000125',
    createdAt: '2026-08-30T07:30:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'exp-002',
    date: '2026-08-29',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    expenseType: 'CONTRACTOR',
    category: 'CARPENTER',
    paidTo: 'Rafiqul Islam',
    contractorId: 'cnt-carpenter-01',
    contractorName: 'Rafiqul Islam',
    amount: 30000,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    description: 'Shuttering work installment for beam and slab casting.',
    reference: 'Work Sheet #W-12',
    voucherId: 'vch-00124',
    voucherNumber: 'CPV-2026-000124',
    createdAt: '2026-08-29T11:00:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'exp-003',
    date: '2026-08-28',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    expenseType: 'LABOUR',
    category: 'DAILY_LABOUR',
    paidTo: 'Daily Labour Sarder (Kashem)',
    amount: 18500,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    description: 'Daily labour wage for 15 workers (Earth filling and curing).',
    reference: 'Site Muster Roll #04',
    voucherId: 'vch-00123',
    voucherNumber: 'CPV-2026-000123',
    createdAt: '2026-08-28T17:00:00Z',
    createdBy: 'Engr. Sohel Rana',
  },
  {
    id: 'exp-004',
    date: '2026-08-27',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    expenseType: 'MATERIAL',
    category: 'ROD',
    paidTo: 'Meghna Steel & Rod Enterprise',
    supplierId: 'sup-bsrm-02',
    supplierName: 'Meghna Steel & Rod Enterprise',
    amount: 145000,
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    description: 'BSRM 16mm & 20mm deformed bar delivery (1.5 Ton).',
    reference: 'Challan #CH-88219',
    voucherId: 'vch-00122',
    voucherNumber: 'CPV-2026-000122',
    createdAt: '2026-08-27T14:30:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'exp-005',
    date: '2026-08-26',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    expenseType: 'CONTRACTOR',
    category: 'ELECTRICIAN',
    paidTo: 'Abul Kalam',
    contractorId: 'cnt-electric-02',
    contractorName: 'Abul Kalam',
    amount: 40000,
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    description: 'Concealed conduit pipe layout and distribution board fitting.',
    reference: 'Bill #EL-45',
    voucherId: 'vch-00121',
    voucherNumber: 'CPV-2026-000121',
    createdAt: '2026-08-26T15:00:00Z',
    createdBy: 'MD. Ilyas',
  }
];

export const initialVouchers: Voucher[] = [
  {
    id: 'vch-00125',
    voucherNumber: 'CPV-2026-000125',
    date: '2026-08-30',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    paidTo: 'Rahman Traders',
    category: 'Cement Purchase (Material)',
    description: '50 bags Crown Cement for 3rd floor casting.',
    amount: 25000,
    amountInWordsBn: convertNumberToWordsBn(25000),
    amountInWordsEn: convertNumberToWordsEn(25000),
    paymentMethod: 'CASH',
    preparedBy: 'MD. Ilyas (Chief Accountant)',
    receivedBy: 'Rahman Traders Representative',
    authorizedBy: 'Eng. S.M. Khalilur Rahman (Managing Director)',
    macSign: 'Approved (M.A.C)',
    drSign: 'Verified (D.R.)',
    dmdSign: 'Passed (D.M.D)',
    transactionId: 'exp-001',
    transactionType: 'EXPENSE',
    status: 'ACTIVE',
    printCount: 1,
    createdAt: '2026-08-30T07:30:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'vch-00124',
    voucherNumber: 'CPV-2026-000124',
    date: '2026-08-29',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    paidTo: 'Rafiqul Islam (Carpenter)',
    category: 'Carpenter Shuttering Payment',
    description: 'Shuttering work installment for beam and slab casting.',
    amount: 30000,
    amountInWordsBn: convertNumberToWordsBn(30000),
    amountInWordsEn: convertNumberToWordsEn(30000),
    paymentMethod: 'CASH',
    preparedBy: 'MD. Ilyas (Chief Accountant)',
    receivedBy: 'Rafiqul Islam',
    authorizedBy: 'Eng. S.M. Khalilur Rahman (Managing Director)',
    macSign: 'Approved (M.A.C)',
    drSign: 'Verified (D.R.)',
    dmdSign: 'Passed (D.M.D)',
    transactionId: 'exp-002',
    transactionType: 'CONTRACTOR_PAYMENT',
    status: 'ACTIVE',
    printCount: 0,
    createdAt: '2026-08-29T11:00:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'vch-00123',
    voucherNumber: 'CPV-2026-000123',
    date: '2026-08-28',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    paidTo: 'Daily Labour Sarder (Kashem)',
    category: 'Daily Labour Wage',
    description: 'Daily labour wage for 15 workers (Earth filling and curing).',
    amount: 18500,
    amountInWordsBn: convertNumberToWordsBn(18500),
    amountInWordsEn: convertNumberToWordsEn(18500),
    paymentMethod: 'CASH',
    preparedBy: 'Engr. Sohel Rana',
    receivedBy: 'Kashem Sarder',
    authorizedBy: 'Eng. S.M. Khalilur Rahman (Managing Director)',
    macSign: 'Approved (M.A.C)',
    drSign: 'Verified (D.R.)',
    dmdSign: 'Passed (D.M.D)',
    transactionId: 'exp-003',
    transactionType: 'EXPENSE',
    status: 'ACTIVE',
    printCount: 0,
    createdAt: '2026-08-28T17:00:00Z',
    createdBy: 'Engr. Sohel Rana',
  },
  {
    id: 'vch-00126',
    voucherNumber: 'CPV-2026-000126',
    date: '2026-09-01',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    paidTo: 'Tutul (Site Travel / Conveyance)',
    category: 'Tutul (Site Travel / Conveyance)',
    description: 'Japan City Tower site visit conveyance and travel bill for engineering team.',
    amount: 5000,
    amountInWordsBn: convertNumberToWordsBn(5000),
    amountInWordsEn: convertNumberToWordsEn(5000),
    paymentMethod: 'CASH',
    preparedBy: 'MD. eleyes',
    receivedBy: 'Tutul',
    authorizedBy: 'Eng. S.M. Khalilur Rahman (Managing Director)',
    transactionId: 'exp-japan-01',
    transactionType: 'MONTHLY_BILL',
    status: 'ACTIVE',
    printCount: 0,
    createdAt: '2026-09-01T10:00:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'vch-mr-001',
    voucherNumber: 'MR-2026-00001',
    date: '2026-08-01',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    paidTo: 'Japan Garden City Ltd.',
    category: 'Money Received (Japan Garden City Funding)',
    description: 'Project development and construction fund received from Japan Garden City Ltd.',
    amount: 1500000,
    amountInWordsBn: convertNumberToWordsBn(1500000),
    amountInWordsEn: convertNumberToWordsEn(1500000),
    paymentMethod: 'BANK',
    preparedBy: 'MD. eleyes',
    receivedBy: 'Japan Garden City Ltd. Representative',
    authorizedBy: 'Eng. S.M. Khalilur Rahman (Managing Director)',
    accountName: 'City Bank Ltd - A/C: 1029384',
    reference: 'CHQ-890123',
    transactionId: 'rec-001',
    transactionType: 'MONEY_RECEIVED',
    status: 'ACTIVE',
    printCount: 0,
    createdAt: '2026-08-01T10:00:00Z',
    createdBy: 'MD. eleyes',
  }
];

export const initialLedger: LedgerEntry[] = [
  {
    id: 'led-001',
    date: '2026-08-01',
    voucherNo: 'MR-2026-00001',
    transactionId: 'rec-001',
    transactionType: 'MONEY_RECEIVED',
    description: 'Funding received from Japan Garden City Ltd.',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    category: 'Money Received',
    received: 1500000,
    payment: 0,
    balance: 1500000,
    person: 'Japan Garden City Ltd.',
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    createdAt: '2026-08-01T10:00:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'led-002',
    date: '2026-08-10',
    voucherNo: 'MR-2026-00002',
    transactionId: 'rec-002',
    transactionType: 'MONEY_RECEIVED',
    description: 'Owner project contribution received',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    category: 'Money Received',
    received: 1000000,
    payment: 0,
    balance: 2500000,
    person: 'Eng. S.M. Khalilur Rahman',
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    createdAt: '2026-08-10T11:00:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'led-003',
    date: '2026-08-27',
    voucherNo: 'CPV-2026-000122',
    transactionId: 'exp-004',
    transactionType: 'EXPENSE',
    description: 'BSRM Deformed Steel Rod procurement',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    category: 'Material - Rod',
    received: 0,
    payment: 145000,
    balance: 2355000,
    person: 'Meghna Steel & Rod Enterprise',
    paymentMethod: 'BANK',
    accountId: 'acc-bank-city',
    accountName: 'City Bank Ltd.',
    createdAt: '2026-08-27T14:30:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'led-004',
    date: '2026-08-28',
    voucherNo: 'CPV-2026-000123',
    transactionId: 'exp-003',
    transactionType: 'EXPENSE',
    description: 'Daily Labour wage payout',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    category: 'Labour - Daily',
    received: 0,
    payment: 18500,
    balance: 2336500,
    person: 'Daily Labour Sarder (Kashem)',
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    createdAt: '2026-08-28T17:00:00Z',
    createdBy: 'Engr. Sohel Rana',
  },
  {
    id: 'led-005',
    date: '2026-08-29',
    voucherNo: 'CPV-2026-000124',
    transactionId: 'exp-002',
    transactionType: 'CONTRACTOR_PAYMENT',
    description: 'Carpenter shuttering installment',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    category: 'Contractor - Carpenter',
    received: 0,
    payment: 30000,
    balance: 2306500,
    person: 'Rafiqul Islam',
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    createdAt: '2026-08-29T11:00:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'led-006',
    date: '2026-08-30',
    voucherNo: 'CPV-2026-000125',
    transactionId: 'exp-001',
    transactionType: 'EXPENSE',
    description: '50 bags Crown Cement purchase for 3rd floor casting',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    category: 'Material - Cement',
    received: 0,
    payment: 25000,
    balance: 2281500,
    person: 'Rahman Traders',
    paymentMethod: 'CASH',
    accountId: 'acc-cash-01',
    accountName: 'Cash in Hand',
    createdAt: '2026-08-30T07:30:00Z',
    createdBy: 'MD. Ilyas',
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    userId: 'demo-super-admin-01',
    userEmail: 'superadmin@skrpproperties.com',
    userName: 'S.M. Khalilur Rahman',
    action: 'SYSTEM_LOGIN',
    module: 'Auth',
    recordId: 'demo-super-admin-01',
    details: 'Super Admin successfully authenticated into SKRP Construction ERP.',
    timestamp: '2026-08-30T07:00:00Z',
  },
  {
    id: 'log-002',
    userId: 'demo-accountant-02',
    userEmail: 'accountant@skrpproperties.com',
    userName: 'MD. Ilyas',
    action: 'CREATE_EXPENSE',
    module: 'Expenses',
    recordId: 'exp-001',
    details: 'Created Expense ৳25,000 for Tokyo Square A (Crown Cement). Linked Voucher CPV-2026-000125.',
    timestamp: '2026-08-30T07:30:00Z',
  },
  {
    id: 'log-003',
    userId: 'demo-accountant-02',
    userEmail: 'accountant@skrpproperties.com',
    userName: 'MD. Ilyas',
    action: 'GENERATE_VOUCHER',
    module: 'Vouchers',
    recordId: 'vch-00125',
    details: 'Generated Cash Payment Voucher CPV-2026-000125 (Paid To: Rahman Traders).',
    timestamp: '2026-08-30T07:30:05Z',
  }
];

export const initialUsers: UserProfile[] = [
  {
    uid: 'user-001',
    email: 'superadmin@skrpproperties.com',
    displayName: 'S.M. Khalilur Rahman (Super Admin)',
    role: 'SUPER_ADMIN',
    phone: '+880 1711-000000',
    assignedProjects: ['ALL'],
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    uid: 'user-002',
    email: 'raihan@skrpproperties.com',
    displayName: 'Khandoker Raihan Islam (Executive / Director)',
    role: 'ADMIN',
    phone: '+880 1711-111222',
    assignedProjects: ['ALL'],
    status: 'ACTIVE',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    uid: 'user-003',
    email: 'madam@skrpproperties.com',
    displayName: 'Director / Madam (Executive)',
    role: 'ADMIN',
    phone: '+880 1711-333444',
    assignedProjects: ['ALL'],
    status: 'ACTIVE',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    uid: 'user-004',
    email: 'accountant@skrpproperties.com',
    displayName: 'Md. Ilyas (Chief Accountant)',
    role: 'ACCOUNTANT',
    phone: '+880 1812-111111',
    assignedProjects: ['ALL'],
    status: 'ACTIVE',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    uid: 'user-005',
    email: 'pm.tokyo@skrpproperties.com',
    displayName: 'Tutul Ahmed (Project Manager)',
    role: 'PROJECT_MANAGER',
    phone: '+880 1913-222222',
    assignedProjects: ['prj-tokyo-a'],
    status: 'ACTIVE',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    uid: 'user-006',
    email: 'engineer@skrpproperties.com',
    displayName: 'Engr. Sohel Rana (Site Engineer)',
    role: 'SITE_ENGINEER',
    phone: '+880 1614-333333',
    assignedProjects: ['prj-tokyo-a'],
    status: 'ACTIVE',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-08-30T00:00:00Z',
  }
];

export const initialMaterials: MaterialItem[] = [
  {
    id: 'mat-001',
    date: '2026-08-30',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    materialName: 'Crown Portland Cement (সিমেন্ট)',
    category: 'CEMENT',
    supplierId: 'sup-rahman-01',
    supplierName: 'Rahman Traders',
    quantity: 50,
    unit: 'Bags (ব্যাগ)',
    rate: 500,
    unitRate: 500,
    totalAmount: 25000,
    totalCost: 25000,
    challanNumber: 'CH-9982',
    paymentStatus: 'PAID',
    expenseId: 'exp-001',
    voucherId: 'vch-00125',
    voucherNumber: 'CPV-2026-000125',
    createdAt: '2026-08-30T07:30:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'mat-002',
    date: '2026-08-27',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    materialName: 'BSRM 16mm & 20mm Deformed Bar (রড)',
    category: 'ROD',
    supplierId: 'sup-bsrm-02',
    supplierName: 'Meghna Steel & Rod Enterprise',
    quantity: 1.5,
    unit: 'Ton (টন)',
    rate: 96667,
    unitRate: 96667,
    totalAmount: 145000,
    totalCost: 145000,
    challanNumber: 'CH-88219',
    paymentStatus: 'PAID',
    expenseId: 'exp-004',
    voucherId: 'vch-00122',
    voucherNumber: 'CPV-2026-000122',
    createdAt: '2026-08-27T14:30:00Z',
    createdBy: 'MD. Ilyas',
  },
  {
    id: 'mat-003',
    date: '2026-08-25',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    materialName: 'First Class Auto Bricks (১ম শ্রেণির ইট)',
    category: 'BRICKS',
    supplierId: 'sup-rahman-01',
    supplierName: 'Rahman Traders',
    quantity: 10,
    unit: 'Thousand (হাজার)',
    rate: 13500,
    unitRate: 13500,
    totalAmount: 135000,
    totalCost: 135000,
    challanNumber: 'CH-44510',
    paymentStatus: 'PAID',
    expenseId: 'exp-005',
    voucherId: 'vch-00121',
    voucherNumber: 'CPV-2026-000121',
    createdAt: '2026-08-25T11:20:00Z',
    createdBy: 'MD. eleyes',
  },
  {
    id: 'mat-004',
    date: '2026-08-22',
    projectId: 'prj-tokyo-a',
    projectName: 'Tokyo Square Convention Center - Project A',
    materialName: 'Sylhet Sand (সিলেট বালু - FM 2.5)',
    category: 'SAND',
    supplierId: 'sup-rahman-01',
    supplierName: 'Rahman Traders',
    quantity: 800,
    unit: 'CFT (ঘনফুট)',
    rate: 65,
    unitRate: 65,
    totalAmount: 52000,
    totalCost: 52000,
    challanNumber: 'CH-33290',
    paymentStatus: 'PAID',
    createdAt: '2026-08-22T09:15:00Z',
    createdBy: 'MD. eleyes',
  }
];
